# makefile for GNU make (automatically generated by makemake)
# NOTE: indent with TAB in GNU makefiles!

# paths are relative to the project directory (current directory during make)

EXE    = yMarketQuote
OBJDIR = o/

# target 'all' (default target)

all : $(EXE)

$(OBJDIR)ymarketquote.o : ymarketquote.c
	gcc $ -c -o $(OBJDIR)ymarketquote.o ymarketquote.c

OBJS = $(OBJDIR)ymarketquote.o

$(EXE) : $(OBJS)
	gcc $(OBJS) $ -lcurl -s -Wall -o $(EXE)

# target 'strip'

strip:
	strip --remove-section=.comment $(EXE)

# target 'clean'

clean:
	-delete $(EXE)
	-delete $(OBJDIR)\*.o
